global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "flask_app"
    static_configs:
      - targets: ["web:5000"]
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]
